// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvFd6GBOgeKHBcV8dhBDcPZ0PfgDVqgQk',
    appId: '1:129690399865:web:3747443614133eba2890a8',
    messagingSenderId: '129690399865',
    projectId: 'zakatyappfyp',
    authDomain: 'zakatyappfyp.firebaseapp.com',
    storageBucket: 'zakatyappfyp.firebasestorage.app',
    measurementId: 'G-Y0ZCN2NWD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzpXVIEtJcegUHuRtwsBhJH5vM7Wu6thc',
    appId: '1:129690399865:android:c0da8293ad77f9a42890a8',
    messagingSenderId: '129690399865',
    projectId: 'zakatyappfyp',
    storageBucket: 'zakatyappfyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARjaKYs-IK_wLBp7FWo4f0plYAjBlaU38',
    appId: '1:129690399865:ios:45be6167165734d32890a8',
    messagingSenderId: '129690399865',
    projectId: 'zakatyappfyp',
    storageBucket: 'zakatyappfyp.firebasestorage.app',
    iosBundleId: 'com.example.fypZakatyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARjaKYs-IK_wLBp7FWo4f0plYAjBlaU38',
    appId: '1:129690399865:ios:45be6167165734d32890a8',
    messagingSenderId: '129690399865',
    projectId: 'zakatyappfyp',
    storageBucket: 'zakatyappfyp.firebasestorage.app',
    iosBundleId: 'com.example.fypZakatyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvFd6GBOgeKHBcV8dhBDcPZ0PfgDVqgQk',
    appId: '1:129690399865:web:675ce723821d91242890a8',
    messagingSenderId: '129690399865',
    projectId: 'zakatyappfyp',
    authDomain: 'zakatyappfyp.firebaseapp.com',
    storageBucket: 'zakatyappfyp.firebasestorage.app',
    measurementId: 'G-ZS840JD8CS',
  );
}
